apiVersion: v1
kind: ReplicationController
metadata:
  name: stl2svx-master
spec:
  replicas: 1
  selector:
    stl2svx-master: "true"
  template:
    metadata:
      labels:
        name: stl2svx-master
        stl2svx-master: "true"
        role: master
    spec:
      containers:
        - name: stl2svx-server
          args: ["-port", "0.0.0.0:45326"]
          image: us.gcr.io/gmlewis/stl2svx-server
          ports:
            - containerPort: 45326
          resources:
            limits:
              cpu: "0.5"
